
language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/users
node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  my_products_tests;' -U postgres
  - psql -U postgres -d my_products_tests -a -f tables.sql

services:
  - postgresql