language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgresql://codex:pg123@localhost:5432/users

before_script:
  - psql -c 'create database  users;' -U postgres
  - psql -U postgres -d users -a -f users.sql

services:
  - postgresql